In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataSet = np.array([[0, 0],[1, 0],[2, 0],[0, 1],[1, 1],[2, 1],[3, 1], [4, 1],[5, 1],[100, 1],[0, 2],[1, 2],[2, 2],[3, 2],
                    [4, 2],[5, 2],[100, 2],[3, 3],[4, 3],[5, 3],[100, 3]])
x = dataSet
N = dataSet.shape[0]


In [42]:
output_data = []

for i in range(0,len(dataSet)):
    if(dataSet[i][1]  <= 2):
        output_data.append(1)
    else:
        output_data.append(-1)
        
output_data = np.array(output_data)
output_data = np.reshape(output_data, (21,1))
output_data

array([[ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [-1],
       [-1],
       [-1]])

In [54]:
c1 = np.asarray(list(filter(lambda x : x[1] <= 2, dataSet)))
c2 = np.asarray(list(filter(lambda x: x[1] > 2, dataSet)))

In [55]:
W = np.asarray([0,0])
W = np.reshape(W, (2,1))
b = np.asarray([1.5])
b = np.reshape(b, (1,1))

W.shape
# b.shape

(2, 1)

In [56]:
def find_accuracy(y):
    predictions = np.zeros(21)
    accuracy = 0
    misclassified_input = []
    
    for i in range(0,len(y)):
        if(y[i][0] > y[i][1]):
            predictions[i] = 1
        else:
            predictions[i] = -1
            
        if(predictions[i] == output_data[i]):
            accuracy+=1
        else:
            misclassified_input.append(dataSet[i])        
    misclassified_input = np.asarray(misclassified_input)
    print(misclassified_input)
    
#     if(len(misclassified_input) < 10):
#         abline(slope = -W[0]/W[1], intercept = -b/W[1])
    
    print(accuracy)
    accuracy = accuracy / N
    print(accuracy * 100)

In [61]:
# Source: https://stackoverflow.com/questions/7941226/how-to-add-line-based-on-slope-and-intercept-in-matplotlib
def abline(slope=-0.00133511/1.92622413, intercept=3.04885766/1.92622413):
    """Plot a line from slope and intercept"""
#     axes = plot.gca()
    
    figure = plt.figure(figsize=(20, 20))
    axes= figure.add_axes([0,0,1,1])
    axes.scatter(c1[:, 0], c1[:, 1], color="blue")
    axes.scatter(c2[:, 0], c2[:, 1], color="red")
    
    x_vals = np.array(axes.get_xlim())
    y_vals = intercept + slope * x_vals
    plt.plot(x_vals, y_vals, '-')
    plt.show()

In [74]:
num_iter = 1
learning_rate = 1e-2
prev_error = np.zeros(21)
epsilon = 1e-3

for k in range(num_iter):
    
    yhat = x.dot(W) + b
    yhat = 1.0/ (1.0 + np.exp(-yhat))
    error = output_data - yhat            # Error term
    W_prev = W
    b_prev = b
    
#     if(abs(np.sum(error) - np.sum(prev_error)) <  epsilon):
#         print("Algorithm Converged")
#     abline(slope = -W[0]/W[1], intercept = -b/W[1])
#         break
        
    delta_w = np.transpose(x).dot(error)
    delta_b = np.sum(error)

    W = W_prev + learning_rate * delta_w
    b = b_prev + learning_rate * delta_b
    
    y =  (-1/W[1]) * (W[0] * x + b)  # w0*x1 + w1*y + b = 0
    find_accuracy(y)
    prev_error = error
    print("iteration {0}, error : {3} , prev_parameters : {1} , updated_parameters : {2} ".format(k+1,[W_prev,b_prev], [W,b] ,np.sum(error)))

[[  0   0]
 [  1   0]
 [  2   0]
 [  1   1]
 [  2   1]
 [  3   1]
 [  4   1]
 [  5   1]
 [100   1]
 [  2   2]
 [  3   2]
 [  4   2]
 [  5   2]
 [100   2]]
7
33.33333333333333
iteration 1, error : 9.387422163094932 , prev_parameters : [array([[-1.61425185],
       [-0.57423645]]), array([[1.58030695]])] , updated_parameters : [array([[-0.4229692 ],
       [-0.51484276]]), array([[1.67418117]])] 


In [73]:
slope = -W[0]/W[1]
slope
# intercept = -b/W[1]
# intercept.shape

array([-2.81112746])

In [ ]:
error = output_data - pred_output
error